namespace Todo.Domain.Entities;

// Minimal, self-issued account — not a real identity system. No email
// verification, no password reset, no rate limiting (flagged as a deferred gap in
// design.md's STRIDE table). Good enough to prove real owner isolation, not more.
public class User
{
    public Guid Id { get; private set; }
    public string Username { get; private set; } = default!;
    // this property is private to prevent accidental exposure of the hash; it is only used internally by AuthService;
    // it is typically a hashed password generated by IPasswordHasher<User> (PBKDF2) and stored in the database
    public string PasswordHash { get; private set; } = default!;

    private User() { }

    public static User Create(string username, string passwordHash) => new()
    {
        Id = Guid.NewGuid(),
        Username = username,
        PasswordHash = passwordHash,
    };
}
